services:
  server:
    image: trantri10503/user-crud-gorm:1.0
    ports:
      - "8080:8080"
    networks:
      - user-network
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB_NAME: postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    networks:
      - user-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  user-network:
    driver: bridge
    name: user-network